const infoById = {
  "1585675": {
    id: 1585675,
    name: "anudari@presscenter.mn",
    username: "anudari@presscenter.mn",
    email: "anudari@presscenter.mn",
    company: 0,
    mergeInto: "admin@presscenter.mn",
  },
  "1587019": {
    id: 1587019,
    name: "Tsolmon",
    username: "Tsolmon",
    email: "tsolmon@presscenter.mn",
    company: 0,
    mergeInto: "admin@presscenter.mn",
  },
  "1591302": {
    id: 1591302,
    name: "Нийтлэлч",
    username: "Нийтлэлч",
    email: "tsoruman@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1609964": {
    id: 1609964,
    name: "Ankhzaya",
    username: "Ankhzaya",
    email: "ankhzaya@presscenter.mn",
    company: 0,
    mergeInto: "admin@presscenter.mn",
  },
  "1611904": {
    id: 1611904,
    name: "НЗДТГ Сургалт судалгаа, олон нийттэй харилцах газар",
    username: "НЗДТГ Сургалт судалгаа, олон нийттэй харилцах газар",
    email: "b_anuka0217@yahoo.com",
    company: 1,
    mergeInto: "",
  },
  "1611964": {
    id: 1611964,
    name: "Тунгаа",
    username: "Тунгаа",
    email: "oyuntungalag68@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1612029": {
    id: 1612029,
    name: "Ариунжаргал",
    username: "Ариунжаргал",
    email: "anji.mgl0612@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1612032": {
    id: 1612032,
    name: "Б.Даваасүрэн",
    username: "Б.Даваасүрэн",
    email: "davka0624@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1612033": {
    id: 1612033,
    name: "Ариунжаргал",
    username: "Ариунжаргал",
    email: "aanjaa10@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1612436": {
    id: 1612436,
    name: "Төрмөнх",
    username: "Төрмөнх",
    email: "newturuu@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1612453": {
    id: 1612453,
    name: "Алим",
    username: "Алим",
    email: "baterdene.ankhzaya@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1612455": {
    id: 1612455,
    name: "Энхтулга",
    username: "Энхтулга",
    email: "ttristone@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1612516": {
    id: 1612516,
    name: "Эрдэнийн Лхагва",
    username: "Эрдэнийн Лхагва",
    email: "lhagvae@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1612733": {
    id: 1612733,
    name: "Д. Лхама",
    username: "Д. Лхама",
    email: "lhamadecatto@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1612990": {
    id: 1612990,
    name: "У.Баттамир",
    username: "У.Баттамир",
    email: "ulambayarbattamir@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1612997": {
    id: 1612997,
    name: "Гуталт муур",
    username: "Гуталт муур",
    email: "oyunsaikhanbold@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613004": {
    id: 1613004,
    name: "Баратабура",
    username: "Баратабура",
    email: "g.batbaatar@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613165": {
    id: 1613165,
    name: "Нямдорж",
    username: "Нямдорж",
    email: "nyamkaa@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1613232": {
    id: 1613232,
    name: "Хишигт",
    username: "Хишигт",
    email: "khishigtbolorerdene@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613234": {
    id: 1613234,
    name: "Баярмаа",
    username: "Баярмаа",
    email: "bmaawol@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613235": {
    id: 1613235,
    name: "Nairamdal",
    username: "Nairamdal",
    email: "bolornairamdal@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613236": {
    id: 1613236,
    name: "ТоМи",
    username: "ТоМи",
    email: "tsendmunkhzul@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613237": {
    id: 1613237,
    name: "Мөнгөө",
    username: "Мөнгөө",
    email: "gmmunguu@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613238": {
    id: 1613238,
    name: "Од",
    username: "Од",
    email: "odongaravbolormaa28@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613239": {
    id: 1613239,
    name: "Хандаа",
    username: "Хандаа",
    email: "khandaagunaajav@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1613385": {
    id: 1613385,
    name: "М.Оргил",
    username: "М.Оргил",
    email: "manlair245@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613387": {
    id: 1613387,
    name: "Энхсүлдэр",
    username: "Энхсүлдэр",
    email: "enhsulder11@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613388": {
    id: 1613388,
    name: "Амгалантуул",
    username: "Амгалантуул",
    email: "amgalantuul08@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613389": {
    id: 1613389,
    name: "Сүх-Эрдэнэ",
    username: "Сүх-Эрдэнэ",
    email: "sukherdene.mff@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613390": {
    id: 1613390,
    name: "Дэлгэрцэцэг",
    username: "Дэлгэрцэцэг",
    email: "erdenesuvd240@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1613391": {
    id: 1613391,
    name: "Хаш-Эрдэнэ",
    username: "Хаш-Эрдэнэ",
    email: "khasherdenebat@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613408": {
    id: 1613408,
    name: "Х.Гэрэлтэх",
    username: "Х.Гэрэлтэх",
    email: "kodonchimeg@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613409": {
    id: 1613409,
    name: "Тэгшжаргал",
    username: "Тэгшжаргал",
    email: "teegi1011@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613411": {
    id: 1613411,
    name: "Т.Намуунболор",
    username: "Т.Намуунболор",
    email: "namuunbolort@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613657": {
    id: 1613657,
    name: "Энхтулга",
    username: "Энхтулга",
    email: "tulgaa_east@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1613733": {
    id: 1613733,
    name: "Анужин",
    username: "Анужин",
    email: "anujin4x@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613734": {
    id: 1613734,
    name: "Г.Мөнх-Эрдэнэ",
    username: "Г.Мөнх-Эрдэнэ",
    email: "gmunkherdene@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613735": {
    id: 1613735,
    name: "Baby Montessorian",
    username: "Baby Montessorian",
    email: "babymontessorian@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613736": {
    id: 1613736,
    name: "Батцэрэн",
    username: "Батцэрэн",
    email: "battserenon@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613739": {
    id: 1613739,
    name: "С.Отгонбат",
    username: "С.Отгонбат",
    email: "s.otgonbat1202@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613740": {
    id: 1613740,
    name: "Lene",
    username: "Lene",
    email: "bbatnemeh@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613746": {
    id: 1613746,
    name: "Соёлын яам",
    username: "Соёлын яам",
    email: "boldoodorj.shirnen@gmail.com",
    company: 1,
    mergeInto: "",
  },
  "1613751": {
    id: 1613751,
    name:
      "Монгол Улсын Ерөнхийлөгчийн Тамгийн Газрын хэвлэл мэдээлэл, олон нийттэй харилцах газар",
    username:
      "Монгол Улсын Ерөнхийлөгчийн Тамгийн Газрын хэвлэл мэдээлэл, олон нийттэй харилцах газар",
    email: "aminaa.kh@president.mn",
    company: 1,
    mergeInto: "",
  },
  "1613755": {
    id: 1613755,
    name: "Ц.Дуламсүрэн",
    username: "Ц.Дуламсүрэн",
    email: "dulamsvren20@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613756": {
    id: 1613756,
    name: "Э. Ариунсайхан",
    username: "Э. Ариунсайхан",
    email: "ariuka.hoho2@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613757": {
    id: 1613757,
    name: "Элбэг",
    username: "Элбэг",
    email: "muugii_7007@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1613764": {
    id: 1613764,
    name: "Michel Tenger",
    username: "Michel Tenger",
    email: "lindaomboo@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1613766": {
    id: 1613766,
    name: "Б. Янжмаа",
    username: "Б. Янжмаа",
    email: "yanjmaaa.b@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1613774": {
    id: 1613774,
    name: "Э. Шүрэнцэцэг",
    username: "Э. Шүрэнцэцэг",
    email: "eshuree0912@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1614164": {
    id: 1614164,
    name: "Байгаль орчин, аялал жуулчлалын яам",
    username: "Байгаль орчин, аялал жуулчлалын яам",
    email: "tsend-ayush@mne.gov.mn",
    company: 1,
    mergeInto: "",
  },
  "1614176": {
    id: 1614176,
    name: "Уул уурхай, хүнд үйлдвэрийн яам",
    username: "Уул уурхай, хүнд үйлдвэрийн яам",
    email: "bayarjavkhlanbaldorj@gmail.com",
    company: 1,
    mergeInto: "",
  },
  "1614177": {
    id: 1614177,
    name: "Хөдөлмөр нийгмийн хамгааллын яам",
    username: "Хөдөлмөр нийгмийн хамгааллын яам",
    email: "battseren@mlsp.gov.mn",
    company: 1,
    mergeInto: "",
  },
  "1614178": {
    id: 1614178,
    name: "Хууль зүй, дотоод хэргийн яам",
    username: "Хууль зүй, дотоод хэргийн яам",
    email: "saturncflr@gmail.com",
    company: 1,
    mergeInto: "",
  },
  "1614179": {
    id: 1614179,
    name: "Хүнс, хөдөө аж ахуй, хөнгөн үйлдвэрийн яам",
    username: "Хүнс, хөдөө аж ахуй, хөнгөн үйлдвэрийн яам",
    email: "mofa.gov999@gmail.com",
    company: 1,
    mergeInto: "",
  },
  "1614180": {
    id: 1614180,
    name: "Эрчим хүчний яам",
    username: "Эрчим хүчний яам",
    email: "moitog@gmail.com",
    company: 1,
    mergeInto: "",
  },
  "1614217": {
    id: 1614217,
    name: "Засгийн газар",
    username: "Засгийн газар",
    email: "naranmunkh@pmo.gov.mn",
    company: 1,
    mergeInto: "",
  },
  "1614245": {
    id: 1614245,
    name: "Харилцаа Холбоо Мэдээллийн Технологийн Газар",
    username: "Харилцаа Холбоо Мэдээллийн Технологийн Газар",
    email: "enkhbaatarurantsetseg@gmail.com",
    company: 1,
    mergeInto: "",
  },
  "1614254": {
    id: 1614254,
    name: "Э.Мөнхбат",
    username: "Э.Мөнхбат",
    email: "ihsanaa15@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1614255": {
    id: 1614255,
    name: "Уянга",
    username: "Уянга",
    email: "uya1204@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1614256": {
    id: 1614256,
    name: "Бичих дуртай",
    username: "Бичих дуртай",
    email: "selenge.bat88@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1614257": {
    id: 1614257,
    name: "С.Саран",
    username: "С.Саран",
    email: "bdm_g10@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1614259": {
    id: 1614259,
    name: "Харцага",
    username: "Харцага",
    email: "hartsaga.maidarjav@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1614390": {
    id: 1614390,
    name: "М. Сакура",
    username: "М. Сакура",
    email: "manda.sura0122@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1614407": {
    id: 1614407,
    name: "Алтанзаяа",
    username: "Алтанзаяа",
    email: "dr.shuud@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1614788": {
    id: 1614788,
    name: "Д. Пүрэвсүрэн",
    username: "Д. Пүрэвсүрэн",
    email: "sahius88@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1614791": {
    id: 1614791,
    name: "П. Отгонтуяа",
    username: "П. Отгонтуяа",
    email: "otgoo.agvaanaa@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1614964": {
    id: 1614964,
    name: "О. Тэмүүлэн",
    username: "О. Тэмүүлэн",
    email: "temuulen.och@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1614965": {
    id: 1614965,
    name: "Erkhemee",
    username: "Erkhemee",
    email: "erkhembayar.1t@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1615039": {
    id: 1615039,
    name: "А. Энх-Ану",
    username: "А. Энх-Ану",
    email: "enxanu@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1615548": {
    id: 1615548,
    name: "Д. Отгонжаргал",
    username: "Д. Отгонжаргал",
    email: "otgonjargaldamba0302@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1615549": {
    id: 1615549,
    name: "Esukhei",
    username: "Esukhei",
    email: "esukhei.boldbaatar@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1616298": {
    id: 1616298,
    name: "Б. Бямба",
    username: "Б. Бямба",
    email: "tolisonin44@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1616299": {
    id: 1616299,
    name: "С. Шүрэнчимэг",
    username: "С. Шүрэнчимэг",
    email: "shurees63@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1619110": {
    id: 1619110,
    name: "Ц. Соно",
    username: "Ц. Соно",
    email: "baasansuren_ts@outlook.com",
    company: 0,
    mergeInto: "",
  },
  "1619789": {
    id: 1619789,
    name: "Улсын Их Хурал",
    username: "Улсын Их Хурал",
    email: "heku2233@gmail.com",
    company: 1,
    mergeInto: "",
  },
  "1619952": {
    id: 1619952,
    name: "Я.Жамсран",
    username: "Я.Жамсран",
    email: "bayamad@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1620244": {
    id: 1620244,
    name: "Bazarkhand",
    username: "Bazarkhand",
    email: "bumerbazak@yahoo.de",
    company: 0,
    mergeInto: "",
  },
  "1620245": {
    id: 1620245,
    name: "Айса. Н",
    username: "Айса. Н",
    email: "namuunaa8944@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1620705": {
    id: 1620705,
    name: "Н. Санчир",
    username: "Н. Санчир",
    email: "nsanchir@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1620706": {
    id: 1620706,
    name: "Пагма-X",
    username: "Пагма-X",
    email: "begii022@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1620708": {
    id: 1620708,
    name: "Tsetseg",
    username: "Tsetseg",
    email: "badamaa413@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1621139": {
    id: 1621139,
    name: "Алирс",
    username: "Алирс",
    email: "cmunhzaya@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1621755": {
    id: 1621755,
    name: "Сульфат модернист",
    username: "Сульфат модернист",
    email: "ganxvv@pm.me",
    company: 0,
    mergeInto: "",
  },
  "1621848": {
    id: 1621848,
    name: "Л. Цецгярич",
    username: "Л. Цецгярич",
    email: "enkhsaruul5189@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1622116": {
    id: 1622116,
    name: "Б. Түвшинжаргал",
    username: "Б. Түвшинжаргал",
    email: "tuvshuu.icc@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1622119": {
    id: 1622119,
    name: "М. Пүрэвдорж",
    username: "М. Пүрэвдорж",
    email: "puujeepudo745@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1623403": {
    id: 1623403,
    name: "Анунгоо",
    username: "Анунгоо",
    email: "anu1234567891010@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1623918": {
    id: 1623918,
    name: "MonaLisa",
    username: "MonaLisa",
    email: "erdenetsetseg.n@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1623926": {
    id: 1623926,
    name: "Пресс Центр",
    username: "Пресс Центр",
    email: "dondolgereltsetseg55@gmail.com",
    company: 1,
    mergeInto: "",
  },
  "1624127": {
    id: 1624127,
    name: "Пресс Центр",
    username: "Пресс Центр",
    email: "gereltsetseg@presscenter.mn",
    company: 1,
    mergeInto: "admin@presscenter.mn",
  },
  "1624192": {
    id: 1624192,
    name: "М. Дархижав",
    username: "М. Дархижав",
    email: "daagiicompass99@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1624193": {
    id: 1624193,
    name: "Г. Анхбаяр",
    username: "Г. Анхбаяр",
    email: "ankaa.rocke@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1624356": {
    id: 1624356,
    name: "Б. Энхрийшагай",
    username: "Б. Энхрийшагай",
    email: "b.enkhriishagai@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1624423": {
    id: 1624423,
    name: "Балбарын Ганхуяг",
    username: "Балбарын Ганхуяг",
    email: "gankhuyag.balbar@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1624424": {
    id: 1624424,
    name: "Х. Александр",
    username: "Х. Александр",
    email: "khuvax@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1624425": {
    id: 1624425,
    name: "Э. Саранзаяа",
    username: "Э. Саранзаяа",
    email: "saranzayamtv@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1624436": {
    id: 1624436,
    name: "Г.Мичидмаа",
    username: "Г.Мичидмаа",
    email: "michee0314@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1625108": {
    id: 1625108,
    name: "Б. Хатанбаатар",
    username: "Б. Хатанбаатар",
    email: "b.hatnaa02@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1625942": {
    id: 1625942,
    name: "Нүүдэлчин Панда",
    username: "Нүүдэлчин Панда",
    email: "diplomatia.kh@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1625944": {
    id: 1625944,
    name: "Khunan",
    username: "Khunan",
    email: "khunanm@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1626028": {
    id: 1626028,
    name: "anujinavaa",
    username: "anujinavaa",
    email: "anujinavaa0222@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1626220": {
    id: 1626220,
    name: "Luvsanjamts Ganchimeg",
    username: "Luvsanjamts Ganchimeg",
    email: "jackfallon119@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1626733": {
    id: 1626733,
    name: "Нямжаргал",
    username: "Нямжаргал",
    email: "nyamkaenhee@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1626967": {
    id: 1626967,
    name: "Монсор",
    username: "Монсор",
    email: "monsor@ubam.mn",
    company: 0,
    mergeInto: "",
  },
  "1626984": {
    id: 1626984,
    name: "Ард Санхүүгийн Нэгдэл",
    username: "Ард Санхүүгийн Нэгдэл",
    email: "michidmaa.b@ardholdings.com",
    company: 1,
    mergeInto: "",
  },
  "1627035": {
    id: 1627035,
    name: "Anyyjinb",
    username: "Anyyjinb",
    email: "anujinbayarbaatar@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1627036": {
    id: 1627036,
    name: "Э. Эрмүүнзаяа",
    username: "Э. Эрмүүнзаяа",
    email: "ermvvne@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1627249": {
    id: 1627249,
    name: "Н. Эрхбаяр",
    username: "Н. Эрхбаяр",
    email: "erheenaranmandah@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1628367": {
    id: 1628367,
    name: "Дарья",
    username: "Дарья",
    email: "amukaenhtur@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1628863": {
    id: 1628863,
    name: "Б. Отгонтөгс",
    username: "Б. Отгонтөгс",
    email: "otgontugsb@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1629161": {
    id: 1629161,
    name: "Б.Хасар",
    username: "Б.Хасар",
    email: "ichmin0124@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1629349": {
    id: 1629349,
    name: "Г. Галбадрах",
    username: "Г. Галбадрах",
    email: "gala_mn@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1629450": {
    id: 1629450,
    name: "Б. Одбаяр",
    username: "Б. Одбаяр",
    email: "ododko13@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1629870": {
    id: 1629870,
    name: "ТэнГэрЛиг Медиа Нэгдэл",
    username: "ТэнГэрЛиг Медиа Нэгдэл",
    email: "zack@tngr.media",
    company: 0,
    mergeInto: "",
  },
  "1630352": {
    id: 1630352,
    name: "Эрка",
    username: "Эрка",
    email: "erkaking18@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1630484": {
    id: 1630484,
    name: "М. Баянцэцэг",
    username: "М. Баянцэцэг",
    email: "mandaa_ganaa@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1630705": {
    id: 1630705,
    name: "Б. Мөнхбат",
    username: "Б. Мөнхбат",
    email: "munkhbatwis@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1631305": {
    id: 1631305,
    name: "Далай",
    username: "Далай",
    email: "dalaicancan@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1631976": {
    id: 1631976,
    name: "Ongi",
    username: "Ongi",
    email: "tu.saranchimeg@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1632334": {
    id: 1632334,
    name: "Sponsored content",
    username: "Sponsored content",
    email: "customer@presscenter.mn",
    company: 0,
    mergeInto: "admin@presscenter.mn",
  },
  "1633846": {
    id: 1633846,
    name: "Inner Baatraa",
    username: "Inner Baatraa",
    email: "baataraa0109@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1633951": {
    id: 1633951,
    name: "Sonor",
    username: "Sonor",
    email: "ella.qwerty92@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1634717": {
    id: 1634717,
    name: "Erdenechuluun",
    username: "Erdenechuluun",
    email: "chuka66chuka@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1634721": {
    id: 1634721,
    name: "Tuvshin",
    username: "Tuvshin",
    email: "tuvshin4097@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1634949": {
    id: 1634949,
    name: "Цогт-Очир",
    username: "Цогт-Очир",
    email: "tsogtochir.nurzed@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1634950": {
    id: 1634950,
    name: "А.Дөлгөөн",
    username: "А.Дөлгөөн",
    email: "altandulguun@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1634957": {
    id: 1634957,
    name: "Винзо",
    username: "Винзо",
    email: "vganzorig@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1635091": {
    id: 1635091,
    name: "Nandialien",
    username: "Nandialien",
    email: "nandin.forbiz@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1636131": {
    id: 1636131,
    name: "Хатнаа",
    username: "Хатнаа",
    email: "badamhatnaa@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1636311": {
    id: 1636311,
    name: "Sunflo",
    username: "Sunflo",
    email: "nomuka.mandakh@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1637642": {
    id: 1637642,
    name: "Номинзул",
    username: "Номинзул",
    email: "nominzul.b99@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1637643": {
    id: 1637643,
    name: "Д. Золзаяа",
    username: "Д. Золзаяа",
    email: "tzoll134@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1641727": {
    id: 1641727,
    name: "UBCab",
    username: "UBCab",
    email: "chinbat@ubcab.mn",
    company: 1,
    mergeInto: "",
  },
  "1642971": {
    id: 1642971,
    name: "Olkhon",
    username: "Olkhon",
    email: "amaraaamar388@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1643995": {
    id: 1643995,
    name: "Б.Гандолгор",
    username: "Б.Гандолгор",
    email: "ganaabat00@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1645856": {
    id: 1645856,
    name: "Энгүй",
    username: "Энгүй",
    email: "nandiash1425@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1650260": {
    id: 1650260,
    name: "Б. Янжиндулам",
    username: "Б. Янжиндулам",
    email: "boloryanjindulam@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1650966": {
    id: 1650966,
    name: "Артгаа",
    username: "Артгаа",
    email: "tumenu8@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1651099": {
    id: 1651099,
    name: "Эрдэнэбаяр",
    username: "Эрдэнэбаяр",
    email: "erkanyam@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1651743": {
    id: 1651743,
    name: "Оюунбат",
    username: "Оюунбат",
    email: "oyunk0711@yahoo.com",
    company: 0,
    mergeInto: "",
  },
  "1653848": {
    id: 1653848,
    name: "Пресс Центр",
    username: "Пресс Центр",
    email: "freelancer@presscenter.mn",
    company: 1,
    mergeInto: "admin@presscenter.mn",
  },
  "1656930": {
    id: 1656930,
    name: "Ori Studios",
    username: "Ori Studios",
    email: "info@oristudios.mn",
    company: 1,
    mergeInto: "",
  },
  "1661114": {
    id: 1661114,
    name: "Халтарын Мөнхбаяр",
    username: "Халтарын Мөнхбаяр",
    email: "muugii.khaagii@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1661115": {
    id: 1661115,
    name: "П.Наранбаяр",
    username: "П.Наранбаяр",
    email: "pnaranbayar@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1665303": {
    id: 1665303,
    name: "M.Batbaatar",
    username: "M.Batbaatar",
    email: "mbatbaatar0118@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1669136": {
    id: 1669136,
    name: "А.Уянга",
    username: "А.Уянга",
    email: "uyangaeagletv@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1670341": {
    id: 1670341,
    name: "Б.Гүнсэнхорол",
    username: "Б.Гүнсэнхорол",
    email: "gunsenkhorol.b@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1670662": {
    id: 1670662,
    name: "О.Анхзаяа",
    username: "О.Анхзаяа",
    email: "ankhzaya126@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1670667": {
    id: 1670667,
    name: "Дэнсмаа",
    username: "Дэнсмаа",
    email: "densmaademberel77@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1671357": {
    id: 1671357,
    name: "Азбилэг Хариад",
    username: "Азбилэг Хариад",
    email: "azbileg075@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1671358": {
    id: 1671358,
    name: "Э.Төртогтох",
    username: "Э.Төртогтох",
    email: "turtogtokhe@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1671515": {
    id: 1671515,
    name: "Б.Баттөр",
    username: "Б.Баттөр",
    email: "batturbatjargal1108@gmail.com",
    company: 0,
    mergeInto: "",
  },
  "1676426": {
    id: 1676426,
    name: "Р.Батчимэг",
    username: "Р.Батчимэг",
    email: "hairmaa99@gmail.com",
    company: 0,
    mergeInto: "",
  },
};


module.exports = infoById;