const sectionCategory = {
  "30807": {
    "display-name": "News",
    name: "News",
    slug: "news",
    "external-id": 30807,
    erxesCategory: "BUGD",
  },
  "31143": {
    "display-name": "Нийгэм",
    name: "Нийгэм",
    slug: "Niigem",
    "external-id": 31143,
    erxesCategory: "BID",
  },
  "31144": {
    "display-name": "Амьдралын хэв маяг",
    name: "Амьдралын хэв маяг",
    slug: "lifestyle",
    "external-id": 31144,
    erxesCategory: "BI",
  },
  "31146": {
    "display-name": "Соёл, Урлаг",
    name: "Соёл, Урлаг",
    slug: "soyol-urlag",
    "external-id": 31146,
    erxesCategory: "BUGD",
  },
  "31147": {
    "display-name": "Спорт",
    name: "Спорт",
    slug: "sport",
    "external-id": 31147,
    erxesCategory: "BUGD",
  },
  "31149": {
    "display-name": "Environment-deleted",
    name: "Environment-deleted",
    slug: "environment",
    "external-id": 31149,
    parent: {
      name: "More-deleted",
      slug: "more",
      "external-id": 31148,
      parent_id: null,
    },
    erxesCategory: "00000",
  },
  "31151": {
    "display-name": "Economics -deleted",
    name: "Economics -deleted",
    slug: "economics",
    "external-id": 31151,
    parent: {
      name: "More-deleted",
      slug: "more",
      "external-id": 31148,
      parent_id: null,
    },
    erxesCategory: "00000",
  },
  "31167": {
    "display-name": "E-Sports",
    name: "E-Sports",
    slug: "e-sport",
    "external-id": 31167,
    parent: {
      name: "Спорт",
      slug: "sport",
      "external-id": 31147,
      parent_id: null,
    },
    erxesCategory: "BUGD",
  },
  "31172": {
    "display-name": "Технологи",
    name: "Технологи",
    slug: "technology",
    "external-id": 31172,
    parent: {
      name: "Амьдралын хэв маяг",
      slug: "lifestyle",
      "external-id": 31144,
      parent_id: null,
    },
    erxesCategory: "BUGD",
  },
  "31852": {
    "display-name": "Байгаль орчин",
    name: "Байгаль орчин",
    slug: "baigali-orchin",
    "external-id": 31852,
    parent: {
      name: "Нийгэм",
      slug: "Niigem",
      "external-id": 31143,
      parent_id: null,
    },
    erxesCategory: "Бид",
  },
  "31854": {
    "display-name": "Эдийн засаг",
    name: "Эдийн засаг",
    slug: "ediin-zasag",
    "external-id": 31854,
    parent: {
      name: "Нийгэм",
      slug: "Niigem",
      "external-id": 31143,
      parent_id: null,
    },
    erxesCategory: "BUGD",
  },
  "31855": {
    "display-name": "Дэлхий дахин",
    name: "Дэлхий дахин",
    slug: "delhii-dahin",
    "external-id": 31855,
    parent: {
      name: "Нийгэм",
      slug: "Niigem",
      "external-id": 31143,
      parent_id: null,
    },
    erxesCategory: "BUGD",
  },
  "31857": {
    "display-name": "Эрүүл мэнд",
    name: "Эрүүл мэнд",
    slug: "eruul-mend",
    "external-id": 31857,
    parent: {
      name: "Амьдралын хэв маяг",
      slug: "lifestyle",
      "external-id": 31144,
      parent_id: null,
    },
    erxesCategory: "BI",
  },
  "31858": {
    "display-name": "Хооллолт",
    name: "Хооллолт",
    slug: "hoollolt",
    "external-id": 31858,
    parent: {
      name: "Амьдралын хэв маяг",
      slug: "lifestyle",
      "external-id": 31144,
      parent_id: null,
    },
    erxesCategory: "BI",
  },
  "31859": {
    "display-name": "Аялал",
    name: "Аялал",
    slug: "aylal",
    "external-id": 31859,
    parent: {
      name: "Амьдралын хэв маяг",
      slug: "lifestyle",
      "external-id": 31144,
      parent_id: null,
    },
    erxesCategory: "BI",
  },
  "31860": {
    "display-name": "Гэр Бүл",
    name: "Гэр Бүл",
    slug: "ger-bul",
    "external-id": 31860,
    parent: {
      name: "Хувь хүний хөгжил",
      slug: "huvi-hunii-hugjil",
      "external-id": 32273,
      parent_id: null,
    },
    erxesCategory: "BI",
  },
  "31861": {
    "display-name": "Боловсрол",
    name: "Боловсрол",
    slug: "bolovsrol",
    "external-id": 31861,
    parent: {
      name: "Хувь хүний хөгжил",
      slug: "huvi-hunii-hugjil",
      "external-id": 32273,
      parent_id: null,
    },
    erxesCategory: "BI",
  },
  "31862": {
    "display-name": "Сэтгэл зүй",
    name: "Сэтгэл зүй",
    slug: "setgel-zui",
    "external-id": 31862,
    parent: {
      name: "Хувь хүний хөгжил",
      slug: "huvi-hunii-hugjil",
      "external-id": 32273,
      parent_id: null,
    },
    erxesCategory: "BI",
  },
  "31907": {
    "display-name": "Бясалгал",
    name: "Бясалгал",
    slug: "byasalgal",
    "external-id": 31907,
    parent: {
      name: "Хувь хүний хөгжил",
      slug: "huvi-hunii-hugjil",
      "external-id": 32273,
      parent_id: null,
    },
    erxesCategory: "BI",
  },
  "31912": {
    "display-name": "Кино",
    name: "Кино",
    slug: "kino",
    "external-id": 31912,
    parent: {
      name: "Соёл, Урлаг",
      slug: "soyol-urlag",
      "external-id": 31146,
      parent_id: null,
    },
    erxesCategory: "BUGD",
  },
  "31913": {
    "display-name": "Хэл шинжлэл",
    name: "Хэл шинжлэл",
    slug: "hel-shinjlel",
    "external-id": 31913,
    parent: {
      name: "Соёл, Урлаг",
      slug: "soyol-urlag",
      "external-id": 31146,
      parent_id: null,
    },
    erxesCategory: "BUGD",
  },
  "31916": {
    "display-name": "Үндэсний спорт",
    name: "Үндэсний спорт",
    slug: "undesnii-sport",
    "external-id": 31916,
    parent: {
      name: "Спорт",
      slug: "sport",
      "external-id": 31147,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "31922": {
    "display-name": "Ковид-19",
    name: "Ковид-19",
    slug: "covid-19",
    "external-id": 31922,
    erxesCategory: "BUGD",
  },
  "32039": {
    "display-name": "Тойм",
    name: "Тойм",
    slug: "tl-dr",
    "external-id": 32039,
    erxesCategory: "BID",
  },
  "32040": {
    "display-name": "Шинжлэх ухаан",
    name: "Шинжлэх ухаан",
    slug: "shinjleh-uhaan",
    "external-id": 32040,
    parent: {
      name: "Амьдралын хэв маяг",
      slug: "lifestyle",
      "external-id": 31144,
      parent_id: null,
    },
    erxesCategory: "BUGD",
  },
  "32272": {
    "display-name": "Улс төр",
    name: "Улс төр",
    slug: "uls-tur",
    "external-id": 32272,
    parent: {
      name: "Нийгэм",
      slug: "Niigem",
      "external-id": 31143,
      parent_id: null,
    },
    erxesCategory: "BUGD",
  },
  "32273": {
    "display-name": "Хувь хүний хөгжил",
    name: "Хувь хүний хөгжил",
    slug: "huvi-hunii-hugjil",
    "external-id": 32273,
    erxesCategory: "BID",
  },
  "32274": {
    "display-name": "Түүх соёл",
    name: "Түүх соёл",
    slug: "tuuh-soyol",
    "external-id": 32274,
    parent: {
      name: "Соёл, Урлаг",
      slug: "soyol-urlag",
      "external-id": 31146,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "32275": {
    "display-name": "Хөгжим",
    name: "Хөгжим",
    slug: "hugjim",
    "external-id": 32275,
    parent: {
      name: "Соёл, Урлаг",
      slug: "soyol-urlag",
      "external-id": 31146,
      parent_id: null,
    },
    erxesCategory: "BUGD",
  },
  "32276": {
    "display-name": "Сагсан бөмбөг",
    name: "Сагсан бөмбөг",
    slug: "sagsan-bumbug",
    "external-id": 32276,
    parent: {
      name: "Спорт",
      slug: "sport",
      "external-id": 31147,
      parent_id: null,
    },
    erxesCategory: "BUGD",
  },
  "32277": {
    "display-name": "Хөл бөмбөг",
    name: "Хөл бөмбөг",
    slug: "hul-bumbug",
    "external-id": 32277,
    parent: {
      name: "Спорт",
      slug: "sport",
      "external-id": 31147,
      parent_id: null,
    },
    erxesCategory: "BUGD",
  },
  "32596": {
    "display-name": "Гэрлэн дохио",
    name: "Гэрлэн дохио",
    slug: "gerlen-dohio",
    "external-id": 32596,
    erxesCategory: "BID",
  },
  "32598": {
    "display-name": "Уулзвар",
    name: "Уулзвар",
    slug: "uulzvar",
    "external-id": 32598,
    erxesCategory: "BID",
  },
  "32599": {
    "display-name": "Зогсоол",
    name: "Зогсоол",
    slug: "zogsool",
    "external-id": 32599,
    erxesCategory: "BID",
  },
  "32600": {
    "display-name": "Амьдралын хэв маягийн мэдээ",
    name: "Амьдралын хэв маягийн мэдээ",
    slug: "lifestyle-news",
    "external-id": 32600,
    parent: {
      name: "Амьдралын хэв маяг",
      slug: "lifestyle",
      "external-id": 31144,
      parent_id: null,
    },
    erxesCategory: "BI",
  },
  "32601": {
    "display-name": "Нийгмийн мэдээ",
    name: "Нийгмийн мэдээ",
    slug: "niigmiin-medee",
    "external-id": 32601,
    parent: {
      name: "Нийгэм",
      slug: "Niigem",
      "external-id": 31143,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "32602": {
    "display-name": "Хувь хүний хөгжлийн мэдээ",
    name: "Хувь хүний хөгжлийн мэдээ",
    slug: "huvi-hunii-hugjliin-medee",
    "external-id": 32602,
    parent: {
      name: "Хувь хүний хөгжил",
      slug: "huvi-hunii-hugjil",
      "external-id": 32273,
      parent_id: null,
    },
    erxesCategory: "BI",
  },
  "32603": {
    "display-name": "Соёл урлагийн мэдээ",
    name: "Соёл урлагийн мэдээ",
    slug: "soyol-urlagiin-medee",
    "external-id": 32603,
    parent: {
      name: "Соёл, Урлаг",
      slug: "soyol-urlag",
      "external-id": 31146,
      parent_id: null,
    },
    erxesCategory: "BUGD",
  },
  "32604": {
    "display-name": "Спортын мэдээ",
    name: "Спортын мэдээ",
    slug: "sportiin-medee",
    "external-id": 32604,
    parent: {
      name: "Спорт",
      slug: "sport",
      "external-id": 31147,
      parent_id: null,
    },
    erxesCategory: "BUGD",
  },
  "34175": {
    "display-name": "Засгийн газар ХМОНХГ- Old",
    name: "Засгийн газар ХМОНХГ- Old",
    slug: "zasgiin gazariin hevlel medeelel",
    "external-id": 34175,
    parent: {
      name: "Мэдэх эрх- Old",
      slug: "medeh erh",
      "external-id": 34174,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34242": {
    "display-name": "Улсын Их Хурал",
    name: "Улсын Их Хурал",
    slug: "ulsiin-ih-hural",
    "external-id": 34242,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34243": {
    "display-name": "Байгаль орчин, аялал жуулчлалын яам",
    name: "Байгаль орчин, аялал жуулчлалын яам",
    slug: "boajya",
    "external-id": 34243,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34281": {
    "display-name": "Агентлаг",
    name: "Агентлаг",
    slug: "agent",
    "external-id": 34281,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34344": {
    "display-name": "Нийтлэл",
    name: "Нийтлэл",
    slug: "chub-niitlel",
    "external-id": 34344,
    erxesCategory: "00000",
  },
  "34354": {
    "display-name": "Мэдэх эрх",
    name: "Мэдэх эрх",
    slug: "medeh-erh",
    "external-id": 34354,
    erxesCategory: "JISE",
  },
  "34356": {
    "display-name": "Барилга, хот байгуулалтын яам",
    name: "Барилга, хот байгуулалтын яам",
    slug: "barilga-hot-baiguulaltiin-yam",
    "external-id": 34356,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34357": {
    "display-name": "Батлан хамгаалах яам",
    name: "Батлан хамгаалах яам",
    slug: "batlan-hamgaalah-yam",
    "external-id": 34357,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34358": {
    "display-name": "Боловсрол, шинжлэх ухааны яам",
    name: "Боловсрол, шинжлэх ухааны яам",
    slug: "bolovsrol-shinjleh-uhaanii-yam",
    "external-id": 34358,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34359": {
    "display-name": "Гадаад харилцааны яам",
    name: "Гадаад харилцааны яам",
    slug: "gadaad-hariltsaanii-yam",
    "external-id": 34359,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34360": {
    "display-name": "Ерөнхийлөгчийн хэвлэл мэдээлэл",
    name: "Ерөнхийлөгчийн хэвлэл мэдээлэл",
    slug: "eronhiilogchiin-hevlel-medeelel",
    "external-id": 34360,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34361": {
    "display-name": "Зам, тээврийн хөгжлийн яам",
    name: "Зам, тээврийн хөгжлийн яам",
    slug: "zam-teevriin-hugjliin-yam",
    "external-id": 34361,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34362": {
    "display-name": "Засгийн газар ХМОНХГ",
    name: "Засгийн газар ХМОНХГ",
    slug: "zasgiin-gazariin-hevlel-medeelel",
    "external-id": 34362,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34363": {
    "display-name": "Сангийн яам",
    name: "Сангийн яам",
    slug: "sangiin-yam",
    "external-id": 34363,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34364": {
    "display-name": "Соёлын яам",
    name: "Соёлын яам",
    slug: "soyoliin-yam",
    "external-id": 34364,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34365": {
    "display-name": "Уул уурхай, хүнд үйлдвэрийн яам",
    name: "Уул уурхай, хүнд үйлдвэрийн яам",
    slug: "uul-uurhai-hund-uildveriin-yam",
    "external-id": 34365,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34366": {
    "display-name": "Хөдөлмөр, нийгмийн хамгааллын яам",
    name: "Хөдөлмөр, нийгмийн хамгааллын яам",
    slug: "hudulmur-niigmiin-hamgaalliin-yam",
    "external-id": 34366,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34367": {
    "display-name": "Хүнс, хөдөө аж ахуй, хөнгөн үйлдвэрийн яам",
    name: "Хүнс, хөдөө аж ахуй, хөнгөн үйлдвэрийн яам",
    slug: "huns-huduu-aj-ahui-hongon-uildveriin-yam",
    "external-id": 34367,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34368": {
    "display-name": "Хууль зүй, дотоод хэргийн яам",
    name: "Хууль зүй, дотоод хэргийн яам",
    slug: "huuli-zui-dotood-hergiin-yam",
    "external-id": 34368,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34369": {
    "display-name": "Эрүүл мэндийн яам",
    name: "Эрүүл мэндийн яам",
    slug: "eruul-mendiin-yam",
    "external-id": 34369,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34370": {
    "display-name": "Эрчим хүчний яам",
    name: "Эрчим хүчний яам",
    slug: "erchim-huchnii-yam",
    "external-id": 34370,
    parent: {
      name: "Мэдэх эрх",
      slug: "medeh-erh",
      "external-id": 34354,
      parent_id: null,
    },
    erxesCategory: "BID",
  },
  "34944": {
    "display-name": "Хүний эрх",
    name: "Хүний эрх",
    slug: "hunii-erh",
    "external-id": 34944,
    parent: {
      name: "Нийгэм",
      slug: "Niigem",
      "external-id": 31143,
      parent_id: null,
    },
    erxesCategory: "BUGD",
  },
  "35978": {
    "display-name": "Цаг агаар",
    name: "Цаг агаар",
    slug: "tsag-agaar",
    "external-id": 35978,
    erxesCategory: "BID",
  },
  "36009": {
    "display-name": "Чөлөөт талбар",
    name: "Чөлөөт талбар",
    slug: "chuluut-talbar",
    "external-id": 36009,
    erxesCategory: "BID",
  },
};

module.exports = sectionCategory;